engines:
  phpcodesniffer:
    enabled: true
  phpmd:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true

exclude_paths:
  - vendor/*
  # JS
  - js/color/*
  - js/jquery/*
  - js/migrate/*
  - js/mobile/*
  - js/qunit/*
  - js/ui/
  # CSS
  - js/mobile/*
  - js/qunit/*
  - js/ui/
